[plugins]
android-application = { id = "com.android.application", version = "8.2.2" }
android-library = { id = "com.android.library", version = "8.2.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.22" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.21" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.0.3" }
palantir-graal = { id = "com.palantir.graal", version = "0.12.0" }
jib = { id = "com.google.cloud.tools.jib", version = "3.4.0" }

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.7.3" }
grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version = "1.60.0" }
grpc-protobuf-lite = { group = "io.grpc", name = "grpc-protobuf-lite", version = "1.60.0" }
grpc-netty = { group = "io.grpc", name = "grpc-netty", version = "1.60.0" }
grpc-okhttp = { group = "io.grpc", name = "grpc-okhttp", version = "1.61.1" }
grpc-testing = { group = "io.grpc", name = "grpc-testing", version = "1.60.0" }
grpc-stub = { group = "io.grpc", name = "grpc-stub", version = "1.60.0" }
grpc-kotlin-stub = { group = "io.grpc", name = "grpc-kotlin-stub", version = "1.4.1" }

protoc = { group = "com.google.protobuf", name = "protoc", version = "3.25.1" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version = "3.25.3" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version = "3.25.3" }
protobuf-java-util = { group = "com.google.protobuf", name = "protobuf-java-util", version = "3.25.1" }
protoc-gen-grpc-java = { group = "io.grpc", name = "protoc-gen-grpc-java", version = "1.61.1" }
protoc-gen-grpc-kotlin = { group = "io.grpc", name = "protoc-gen-grpc-kotlin", version = "1.4.1" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.8.2" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version = "1.5.4" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version = "1.5.4" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version = "1.5.4" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version = "1.5.4" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version = "1.5.6" }

kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version = "1.9.22" }
