[versions]
grpc-java = "1.76.0"
protobuf-java = "4.33.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.20" }
protobuf = { id = "com.google.protobuf", version = "0.9.5" }
test-retry = { id = "org.gradle.test-retry", version = "1.5.7" }
publish-plugin = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
qoomon-git-versioning = { id = "me.qoomon.git-versioning", version = "6.4.3" }
kotlin-power-assert = { id = "com.bnorm.power.kotlin-power-assert", version = "0.13.0" }

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-coroutines-core-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version = "1.10.2" }

grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpc-java" }
grpc-protobuf-lite = { group = "io.grpc", name = "grpc-protobuf-lite", version.ref = "grpc-java" }
grpc-alts = { group = "io.grpc", name = "grpc-alts", version.ref = "grpc-java" }
grpc-auth = { group = "io.grpc", name = "grpc-auth", version.ref = "grpc-java" }
grpc-netty = { group = "io.grpc", name = "grpc-netty", version.ref = "grpc-java" }
grpc-okhttp = { group = "io.grpc", name = "grpc-okhttp", version.ref = "grpc-java" }
grpc-testing = { group = "io.grpc", name = "grpc-testing", version.ref = "grpc-java" }
grpc-stub = { group = "io.grpc", name = "grpc-stub", version.ref = "grpc-java" }
grpc-inprocess = { group = "io.grpc", name = "grpc-inprocess", version.ref = "grpc-java" }
protoc-gen-grpc-java = { group = "io.grpc", name = "protoc-gen-grpc-java", version.ref = "grpc-java" }

protoc = { group = "com.google.protobuf", name = "protoc",  version.ref = "protobuf-java" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf-java" }

kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version = "2.2.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.10.2" }
guava = { group = "com.google.guava", name = "guava", version = "33.0.0-jre" }
jimfs = { group = "com.google.jimfs", name = "jimfs", version = "1.3.0" }
protobuf-gradle-plugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version = "0.9.5" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.13.4" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.13.4" }
mockito-core = { group = "org.mockito", name = "mockito-core", version = "5.17.0" }
truth = { group = "com.google.truth", name = "truth", version = "1.4.4" }
truth-proto-extension = { group = "com.google.truth.extensions", name = "truth-proto-extension", version = "1.4.4" }
okhttp = { group = "com.squareup.okhttp", name = "okhttp", version = "2.7.5" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version = "1.21.3" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.17" }
gradle-test-kit = { group = "org.gradle", name = "gradle-test-kit", version = "6.1" }
gradle-tooling-api = { group = "org.gradle", name = "gradle-tooling-api", version = "9.0.0" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.15.1" }
