name: Gradle Build on ARM
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  gradle_arm:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v4
    - name: test_on_arm
      continue-on-error: true
      uses: uraimo/run-on-arch-action@v2.6.0
      with:
        arch: aarch64
        distro: ubuntu18.04

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        install: |
          apt-get update -q -y
          apt-get install openjdk-8-jdk -q -y

        # Build library using gradle
        run: |
          ./gradlew --console=plain build
    - name: test_on_arm_retry
      if: steps.test_on_arm.outcome=='failure'
      uses: uraimo/run-on-arch-action@v2.6.0
      with:
        arch: aarch64
        distro: ubuntu18.04

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        install: |
          apt-get update -q -y
          apt-get install openjdk-8-jdk -q -y

        # Build library using gradle
        run: |
          ./gradlew --console=plain build
